### ISSUE TITLE
app not working

### ISSUE THREAD

**Issue by yaronmil** [angular-university/ngrx-course#7]
running the lates version (master)
yield the folling error :

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 12:42 in the original .ts file), resolving symbol compose in D:/vasco/ngrx-c
ourse/node_modules/@ngrx/core/compose.d.ts, resolving symbol AppModule in D:/vasco/ngrx-course/src/app/app.module.ts, resolving symbol AppModule in D:/vasco/ngrx-course/src/app/app.module.ts, resolving symbol AppModule in D:/vasco/ngrx-course/src/app/app.module.ts,
resolving symbol AppModule in D:/vasco/ngrx-course/src/app/app.module.ts, resolving symbol AppModule in D:/vasco/ngrx-course/src/app/app.module.ts

ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (D:\vasco\ngrx-course\node_modules\typescript\lib\typescript.js:9514:20)
    at Object.createCompilerHost (D:\vasco\ngrx-course\node_modules\typescript\lib\typescript.js:63770:26)
    at Object.ngcLoader (D:\vasco\ngrx-course\node_modules\@ngtools\webpack\src\loader.js:338:33)
 @ multi webpack-dev-server/client?http://localhost:4201 ./src/main.ts

ERROR in ./src/polyfills.ts
Module build failed: TypeError: Cannot read property 'newLine' of undefined
    at Object.getNewLineCharacter (D:\vasco\ngrx-course\node_modules\typescript\lib\typescript.js:9514:20)
    at Object.createCompilerHost (D:\vasco\ngrx-course\node_modules\typescript\lib\typescript.js:63770:26)
    at Object.ngcLoader (D:\vasco\ngrx-course\node_modules\@ngtools\webpack\src\loader.js:338:33)
 @ multi ./src/polyfills.ts
webpack: Failed to compile.

**Comment by ZikZakJainy** [comment]
I am also facing same error.

**Comment by daiando** [comment]
I got same error.

**Comment by JimmyOnGitHub** [comment]
This is ridiculous ,why hasn't this been addressed?

**Comment by jhades** [comment]
Hello everyone, this looks like an issue in the CLI or in the toolchain that uses it. If we hit space in a typescript file that triggers a rebuild of the same program, but this time it works, even if we didn't change the program.

**Comment by jhades** [comment]
The following was put in place to improve the situation: the definition of the reducer was put outside the module file, into an external file. This still throws the error message but the application now runs.

This issue will eventually disappear as the CLI evolves, if anyone is still facing this issue I advise updating the CLI. KR Vasco

**Comment by hairylee** [comment]
Hi,

I found a little workaround to get rid of the error message.

in app.module.ts add: 
`export function getComposedReducers(state: any, action: any) {
  return reducer(state, action);
}`

in app.module.ts use the new Function instead of the compose constant:
`...
StoreModule.provideStore(getComposedReducers, INITIAL_APPLICATION_STATE),
...`

**Comment by hairylee** [comment]
Hi,

I found a little workaround to get rid of the error message.

in app.module.ts add: 
`export function getComposedReducers(state: any, action: any) {
  return reducer(state, action);
}`

in app.module.ts use the new Function instead of the compose constant:
`...
StoreModule.provideStore(getComposedReducers, INITIAL_APPLICATION_STATE),
...`
